services:
  cover-updater:
    container_name: cover-updater
    image: bperel/duck-cover-id-updater
    environment:
      MYSQL_COVER_INFO_HOST: db
      MYSQL_COVER_INFO_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_COVER_INFO_DATABASE: cover_info
      MYSQL_COA_HOST: db
      MYSQL_COA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_COA_DATABASE: coa
      PASTEC_HOST: pastec
      PASTEC_PORT: 4212
      PASTEC_CONTAINER_HOME: /pastec/build
    networks:
      - dm-server_db-network
      - dm-server_cover-id-network

networks:
  dm-server_db-network:
    external: true
  dm-server_cover-id-network:
    external: true
