/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/admin/bookstores': RouteRecordInfo<'/admin/bookstores', '/admin/bookstores', Record<never, never>, Record<never, never>>,
    '/admin/edges/progress': RouteRecordInfo<'/admin/edges/progress', '/admin/edges/progress', Record<never, never>, Record<never, never>>,
    '/admin/generate-sprites': RouteRecordInfo<'/admin/generate-sprites', '/admin/generate-sprites', Record<never, never>, Record<never, never>>,
    '/admin/presentation-text/[decision]': RouteRecordInfo<'/admin/presentation-text/[decision]', '/admin/presentation-text/:decision', { decision: ParamValue<true> }, { decision: ParamValue<false> }>,
    '/bookcase/[...all]': RouteRecordInfo<'/bookcase/[...all]', '/bookcase/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/bookcase/afficher/[username]': RouteRecordInfo<'/bookcase/afficher/[username]', '/bookcase/afficher/:username', { username: ParamValue<true> }, { username: ParamValue<false> }>,
    '/bookcase/contributors': RouteRecordInfo<'/bookcase/contributors', '/bookcase/contributors', Record<never, never>, Record<never, never>>,
    '/bookcase/options': RouteRecordInfo<'/bookcase/options', '/bookcase/options', Record<never, never>, Record<never, never>>,
    '/bookcase/show/[username]': RouteRecordInfo<'/bookcase/show/[username]', '/bookcase/show/:username', { username: ParamValue<true> }, { username: ParamValue<false> }>,
    '/bookstores/': RouteRecordInfo<'/bookstores/', '/bookstores', Record<never, never>, Record<never, never>>,
    '/collection/account': RouteRecordInfo<'/collection/account', '/collection/account', Record<never, never>, Record<never, never>>,
    '/collection/afficher/[...all]': RouteRecordInfo<'/collection/afficher/[...all]', '/collection/afficher/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/collection/duplicates': RouteRecordInfo<'/collection/duplicates', '/collection/duplicates', Record<never, never>, Record<never, never>>,
    '/collection/show/[...all]': RouteRecordInfo<'/collection/show/[...all]', '/collection/show/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/collection/show/new': RouteRecordInfo<'/collection/show/new', '/collection/show/new', Record<never, never>, Record<never, never>>,
    '/collection/subscriptions': RouteRecordInfo<'/collection/subscriptions', '/collection/subscriptions', Record<never, never>, Record<never, never>>,
    '/collection/user/[username]/[[...all]]': RouteRecordInfo<'/collection/user/[username]/[[...all]]', '/collection/user/:username/:all(.*)?', { username: ParamValue<true>, all?: ParamValueZeroOrOne<true> }, { username: ParamValue<false>, all?: ParamValueZeroOrOne<false> }>,
    '/demo': RouteRecordInfo<'/demo', '/demo', Record<never, never>, Record<never, never>>,
    '/expand/marketplace': RouteRecordInfo<'/expand/marketplace', '/expand/marketplace', Record<never, never>, Record<never, never>>,
    '/expand/suggestions': RouteRecordInfo<'/expand/suggestions', '/expand/suggestions', Record<never, never>, Record<never, never>>,
    '/forgot/': RouteRecordInfo<'/forgot/', '/forgot', Record<never, never>, Record<never, never>>,
    '/forgot/[token]': RouteRecordInfo<'/forgot/[token]', '/forgot/:token', { token: ParamValue<true> }, { token: ParamValue<false> }>,
    '/image-search-test': RouteRecordInfo<'/image-search-test', '/image-search-test', Record<never, never>, Record<never, never>>,
    '/inducks-import': RouteRecordInfo<'/inducks-import', '/inducks-import', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/print/': RouteRecordInfo<'/print/', '/print', Record<never, never>, Record<never, never>>,
    '/print/classic': RouteRecordInfo<'/print/classic', '/print/classic', Record<never, never>, Record<never, never>>,
    '/print/collectable': RouteRecordInfo<'/print/collectable', '/print/collectable', Record<never, never>, Record<never, never>>,
    '/privacy': RouteRecordInfo<'/privacy', '/privacy', Record<never, never>, Record<never, never>>,
    '/signup': RouteRecordInfo<'/signup', '/signup', Record<never, never>, Record<never, never>>,
    '/stats/authors': RouteRecordInfo<'/stats/authors', '/stats/authors', Record<never, never>, Record<never, never>>,
    '/stats/conditions': RouteRecordInfo<'/stats/conditions', '/stats/conditions', Record<never, never>, Record<never, never>>,
    '/stats/general': RouteRecordInfo<'/stats/general', '/stats/general', Record<never, never>, Record<never, never>>,
    '/stats/possessions': RouteRecordInfo<'/stats/possessions', '/stats/possessions', Record<never, never>, Record<never, never>>,
    '/stats/publications': RouteRecordInfo<'/stats/publications', '/stats/publications', Record<never, never>, Record<never, never>>,
    '/stats/purchases': RouteRecordInfo<'/stats/purchases', '/stats/purchases', Record<never, never>, Record<never, never>>,
  }
}
