version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/api"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/prisma-schemas"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/types"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "daily"
