/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BBadge: typeof import('bootstrap-vue-next')['BBadge']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BFormTextarea: typeof import('bootstrap-vue-next')['BFormTextarea']
    BImg: typeof import('bootstrap-vue-next')['BImg']
    Book: typeof import('./src/components/Book.vue')['default']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    BTab: typeof import('bootstrap-vue-next')['BTab']
    BTabs: typeof import('bootstrap-vue-next')['BTabs']
    InducksStory: typeof import('./src/components/InducksStory.vue')['default']
    Issue: typeof import('./src/components/Issue.vue')['default']
    Publication: typeof import('./src/components/Publication.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadWidget: typeof import('./src/components/UploadWidget.vue')['default']
  }
}
