// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    Accordion: typeof import("./src/components/Accordion.vue")["default"];
    Ago: typeof import("./src/components/Ago.vue")["default"];
    AuthorList: typeof import("./src/components/AuthorList.vue")["default"];
    Banner: typeof import("./src/components/Banner.vue")["default"];
    Bare: typeof import("./src/layouts/bare.vue")["default"];
    Book: typeof import("./src/components/Book.vue")["default"];
    Bookcase: typeof import("./src/components/Bookcase.vue")["default"];
    BookcaseMenu: typeof import("./src/components/menus/BookcaseMenu.vue")["default"];
    BookcasePopover: typeof import("./src/components/BookcasePopover.vue")["default"];
    CollectionMenu: typeof import("./src/components/menus/CollectionMenu.vue")["default"];
    Condition: typeof import("./src/components/Condition.vue")["default"];
    ContextMenuOnSaleByOthers: typeof import("./src/components/ContextMenuOnSaleByOthers.vue")["default"];
    ContextMenuOwnCollection: typeof import("./src/components/ContextMenuOwnCollection.vue")["default"];
    Counter: typeof import("./src/components/Counter.vue")["default"];
    Country: typeof import("./src/components/Country.vue")["default"];
    Default: typeof import("./src/layouts/default.vue")["default"];
    Edge: typeof import("./src/components/Edge.vue")["default"];
    EdgeContents: typeof import("./src/components/EdgeContents.vue")["default"];
    Event: typeof import("./src/components/Event.vue")["default"];
    "Event.story": typeof import("./src/components/Event.story.vue")["default"];
    ExpandMenu: typeof import("./src/components/menus/ExpandMenu.vue")["default"];
    Footer: typeof import("./src/components/Footer.vue")["default"];
    InducksStory: typeof import("./src/components/InducksStory.vue")["default"];
    Issue: typeof import("./src/components/Issue.vue")["default"];
    IssueDetailsPopover: typeof import("./src/components/IssueDetailsPopover.vue")["default"];
    IssueEdgePopover: typeof import("./src/components/IssueEdgePopover.vue")["default"];
    IssueList: typeof import("./src/components/IssueList.vue")["default"];
    "IssueList.story": typeof import("./src/components/IssueList.story.vue")["default"];
    IssueSearch: typeof import("./src/components/IssueSearch.vue")["default"];
    LastPublishedEdges: typeof import("./src/components/LastPublishedEdges.vue")["default"];
    LastPurchases: typeof import("./src/components/LastPurchases.vue")["default"];
    LeftPanel: typeof import("./src/components/LeftPanel.vue")["default"];
    LinkToCollectionIfNoIssue: typeof import("./src/components/LinkToCollectionIfNoIssue.vue")["default"];
    Manage: typeof import("./src/components/Manage.vue")["default"];
    MarketplaceBuyerInfo: typeof import("./src/components/MarketplaceBuyerInfo.vue")["default"];
    MarketplaceSellerInfo: typeof import("./src/components/MarketplaceSellerInfo.vue")["default"];
    Medal: typeof import("./src/components/Medal.vue")["default"];
    MedalProgress: typeof import("./src/components/MedalProgress.vue")["default"];
    Menu: typeof import("./src/components/Menu.vue")["default"];
    Navigation: typeof import("./src/components/Navigation.vue")["default"];
    NavigationItem: typeof import("./src/components/NavigationItem.vue")["default"];
    NavigationItemGroup: typeof import("./src/components/NavigationItemGroup.vue")["default"];
    OtherIssues: typeof import("./src/components/OtherIssues.vue")["default"];
    Popover: typeof import("./src/components/Popover.vue")["default"];
    PrintHeader: typeof import("./src/components/PrintHeader.vue")["default"];
    Publication: typeof import("./src/components/Publication.vue")["default"];
    PublicationList: typeof import("./src/components/PublicationList.vue")["default"];
    PublicationSelect: typeof import("./src/components/PublicationSelect.vue")["default"];
    RecentEvents: typeof import("./src/components/RecentEvents.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SharePage: typeof import("./src/components/SharePage.vue")["default"];
    ShortStats: typeof import("./src/components/ShortStats.vue")["default"];
    StarRating: typeof import("./src/components/StarRating.vue")["default"];
    StatsMenu: typeof import("./src/components/menus/StatsMenu.vue")["default"];
    StoryList: typeof import("./src/components/StoryList.vue")["default"];
    Subscription: typeof import("./src/components/Subscription.vue")["default"];
    SuggestionList: typeof import("./src/components/SuggestionList.vue")["default"];
    SwitchLocale: typeof import("./src/components/SwitchLocale.vue")["default"];
    UploadableEdgesCarousel: typeof import("./src/components/UploadableEdgesCarousel.vue")["default"];
    UserPopover: typeof import("./src/components/UserPopover.vue")["default"];
    ViewBookcase: typeof import("./src/components/ViewBookcase.vue")["default"];
    Watch: typeof import("./src/components/Watch.vue")["default"];
  }
}
