FROM php:7.4-fpm
MAINTAINER Bruno Perel

RUN apt-get update \
 && apt-get install -y \
      git wget unzip \
      net-tools inetutils-ping inetutils-telnet \
      libpng-dev libfreetype6-dev libmcrypt-dev libjpeg-dev libpng-dev libicu-dev \
 && apt-get clean

RUN pecl install apcu xdebug && \
    echo "extension=apcu.so" > /usr/local/etc/php/conf.d/apcu.ini && \
    docker-php-ext-configure gd &&\
    docker-php-ext-install -j$(nproc) opcache intl && \
    docker-php-ext-enable xdebug

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
