services:

  db:
    container_name: db
    image: "mariadb:11.4"
    restart: always
    volumes:
      - db:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - "64999:3306"
    env_file:
      - .env
    command:
      [
        'mariadbd',
        '--character-set-server=utf8',
        '--collation-server=utf8_unicode_ci'
      ]
    networks:
      - db-network

networks:
  db-network:
    name: db-network
    driver: bridge

volumes:
  db:
