services:
  caddy:
    container_name: monitoring-caddy
    image: ghcr.io/bperel/monitoring-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - monitoring-network

  grafana:
    container_name: monitoring-grafana
    image: ghcr.io/bperel/monitoring-grafana
    restart: always
    env_file:
      - .env
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring-network

  prometheus:
    container_name: monitoring-prometheus
    image: ghcr.io/bperel/monitoring-prometheus
    restart: always
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=30d
      - --web.enable-remote-write-receiver
    volumes:
      - prometheus_data:/prometheus
    networks:
      - monitoring-network

  loki:
    container_name: monitoring-loki
    image: ghcr.io/bperel/monitoring-loki
    restart: always
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - loki_data:/loki
    networks:
      - monitoring-network

  blackbox:
    container_name: monitoring-blackbox
    image: ghcr.io/bperel/monitoring-blackbox
    restart: always
    command:
      - --config.file=/etc/blackbox/blackbox.yml
    networks:
      - monitoring-network

  json-exporter:
    container_name: monitoring-json-exporter
    image: ghcr.io/bperel/monitoring-json-exporter
    restart: always
    command:
      - --config.file=/etc/json-exporter/config.yml
    networks:
      - monitoring-network

volumes:
  caddy_data:
  caddy_config:
  grafana_data:
  prometheus_data:
  loki_data:

networks:
  monitoring-network:
    name: monitoring-network
