services:
  stats-updater:
    init: true
    container_name: stats-updater
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: 'run index.ts'
    volumes:
      - .:/home/bun/app
      - inducks_data:/tmp/inducks
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: stats
      MYSQL_DATABASE_NEW: stats_new
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - db-network

volumes:
  inducks_data:
networks:
  db-network:
    external: true
