version: '3.4'
services:
  db:
    restart: always
    image: mariadb:10.5
    container_name: duckguessr-db
    ports:
      - "64098:3306"
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: duckguessr
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    networks:
      - prisma-clients_db-network

volumes:
  db:
