name: duckguessr-api

services:
  db:
    restart: always
    image: mariadb:12.2
    container_name: duckguessr-db
    ports:
      - "64098:3306"
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: duckguessr
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MARIADB_AUTO_UPGRADE: 1
    networks:
      - db-network

volumes:
  db:
networks:
  db-network:
    external: true
