/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/admin/bookstores': RouteRecordInfo<
      '/admin/bookstores',
      '/admin/bookstores',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/edges/progress': RouteRecordInfo<
      '/admin/edges/progress',
      '/admin/edges/progress',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/generate-sprites': RouteRecordInfo<
      '/admin/generate-sprites',
      '/admin/generate-sprites',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/presentation-text/[decision]': RouteRecordInfo<
      '/admin/presentation-text/[decision]',
      '/admin/presentation-text/:decision',
      { decision: ParamValue<true> },
      { decision: ParamValue<false> },
      | never
    >,
    '/bookcase/[...all]': RouteRecordInfo<
      '/bookcase/[...all]',
      '/bookcase/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/bookcase/afficher/[username]': RouteRecordInfo<
      '/bookcase/afficher/[username]',
      '/bookcase/afficher/:username',
      { username: ParamValue<true> },
      { username: ParamValue<false> },
      | never
    >,
    '/bookcase/contributors': RouteRecordInfo<
      '/bookcase/contributors',
      '/bookcase/contributors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bookcase/options': RouteRecordInfo<
      '/bookcase/options',
      '/bookcase/options',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bookcase/show/[username]': RouteRecordInfo<
      '/bookcase/show/[username]',
      '/bookcase/show/:username',
      { username: ParamValue<true> },
      { username: ParamValue<false> },
      | never
    >,
    '/bookstores/': RouteRecordInfo<
      '/bookstores/',
      '/bookstores',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collection/account': RouteRecordInfo<
      '/collection/account',
      '/collection/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collection/afficher/[...all]': RouteRecordInfo<
      '/collection/afficher/[...all]',
      '/collection/afficher/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/collection/duplicates': RouteRecordInfo<
      '/collection/duplicates',
      '/collection/duplicates',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collection/show/[...all]': RouteRecordInfo<
      '/collection/show/[...all]',
      '/collection/show/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/collection/show/new': RouteRecordInfo<
      '/collection/show/new',
      '/collection/show/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collection/subscriptions': RouteRecordInfo<
      '/collection/subscriptions',
      '/collection/subscriptions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collection/user/[username]/[[...all]]': RouteRecordInfo<
      '/collection/user/[username]/[[...all]]',
      '/collection/user/:username/:all(.*)?',
      { username: ParamValue<true>, all?: ParamValueZeroOrOne<true> },
      { username: ParamValue<false>, all?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/demo': RouteRecordInfo<
      '/demo',
      '/demo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/expand/marketplace': RouteRecordInfo<
      '/expand/marketplace',
      '/expand/marketplace',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/expand/suggestions': RouteRecordInfo<
      '/expand/suggestions',
      '/expand/suggestions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/forgot/': RouteRecordInfo<
      '/forgot/',
      '/forgot',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/forgot/[token]': RouteRecordInfo<
      '/forgot/[token]',
      '/forgot/:token',
      { token: ParamValue<true> },
      { token: ParamValue<false> },
      | never
    >,
    '/image-search-test': RouteRecordInfo<
      '/image-search-test',
      '/image-search-test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inducks-import': RouteRecordInfo<
      '/inducks-import',
      '/inducks-import',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/print/': RouteRecordInfo<
      '/print/',
      '/print',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/print/classic': RouteRecordInfo<
      '/print/classic',
      '/print/classic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/print/collectable': RouteRecordInfo<
      '/print/collectable',
      '/print/collectable',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/privacy': RouteRecordInfo<
      '/privacy',
      '/privacy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/signup': RouteRecordInfo<
      '/signup',
      '/signup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/stats/authors': RouteRecordInfo<
      '/stats/authors',
      '/stats/authors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/stats/conditions': RouteRecordInfo<
      '/stats/conditions',
      '/stats/conditions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/stats/general': RouteRecordInfo<
      '/stats/general',
      '/stats/general',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/stats/possessions': RouteRecordInfo<
      '/stats/possessions',
      '/stats/possessions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/stats/publications': RouteRecordInfo<
      '/stats/publications',
      '/stats/publications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/stats/purchases': RouteRecordInfo<
      '/stats/purchases',
      '/stats/purchases',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/admin/bookstores.vue': {
      routes:
        | '/admin/bookstores'
      views:
        | never
    }
    'src/pages/admin/edges/progress.vue': {
      routes:
        | '/admin/edges/progress'
      views:
        | never
    }
    'src/pages/admin/generate-sprites.vue': {
      routes:
        | '/admin/generate-sprites'
      views:
        | never
    }
    'src/pages/admin/presentation-text/[decision].vue': {
      routes:
        | '/admin/presentation-text/[decision]'
      views:
        | never
    }
    'src/pages/bookcase/[...all].vue': {
      routes:
        | '/bookcase/[...all]'
      views:
        | never
    }
    'src/pages/bookcase/afficher/[username].vue': {
      routes:
        | '/bookcase/afficher/[username]'
      views:
        | never
    }
    'src/pages/bookcase/contributors.vue': {
      routes:
        | '/bookcase/contributors'
      views:
        | never
    }
    'src/pages/bookcase/options.vue': {
      routes:
        | '/bookcase/options'
      views:
        | never
    }
    'src/pages/bookcase/show/[username].vue': {
      routes:
        | '/bookcase/show/[username]'
      views:
        | never
    }
    'src/pages/bookstores/index.vue': {
      routes:
        | '/bookstores/'
      views:
        | never
    }
    'src/pages/collection/account.vue': {
      routes:
        | '/collection/account'
      views:
        | never
    }
    'src/pages/collection/afficher/[...all].vue': {
      routes:
        | '/collection/afficher/[...all]'
      views:
        | never
    }
    'src/pages/collection/duplicates.vue': {
      routes:
        | '/collection/duplicates'
      views:
        | never
    }
    'src/pages/collection/show/[...all].vue': {
      routes:
        | '/collection/show/[...all]'
      views:
        | never
    }
    'src/pages/collection/show/new.vue': {
      routes:
        | '/collection/show/new'
      views:
        | never
    }
    'src/pages/collection/subscriptions.vue': {
      routes:
        | '/collection/subscriptions'
      views:
        | never
    }
    'src/pages/collection/user/[username]/[[...all]].vue': {
      routes:
        | '/collection/user/[username]/[[...all]]'
      views:
        | never
    }
    'src/pages/demo.vue': {
      routes:
        | '/demo'
      views:
        | never
    }
    'src/pages/expand/marketplace.vue': {
      routes:
        | '/expand/marketplace'
      views:
        | never
    }
    'src/pages/expand/suggestions.vue': {
      routes:
        | '/expand/suggestions'
      views:
        | never
    }
    'src/pages/forgot/index.vue': {
      routes:
        | '/forgot/'
      views:
        | never
    }
    'src/pages/forgot/[token].vue': {
      routes:
        | '/forgot/[token]'
      views:
        | never
    }
    'src/pages/image-search-test.vue': {
      routes:
        | '/image-search-test'
      views:
        | never
    }
    'src/pages/inducks-import.vue': {
      routes:
        | '/inducks-import'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/print/index.vue': {
      routes:
        | '/print/'
      views:
        | never
    }
    'src/pages/print/classic.vue': {
      routes:
        | '/print/classic'
      views:
        | never
    }
    'src/pages/print/collectable.vue': {
      routes:
        | '/print/collectable'
      views:
        | never
    }
    'src/pages/privacy.vue': {
      routes:
        | '/privacy'
      views:
        | never
    }
    'src/pages/signup.vue': {
      routes:
        | '/signup'
      views:
        | never
    }
    'src/pages/stats/authors.vue': {
      routes:
        | '/stats/authors'
      views:
        | never
    }
    'src/pages/stats/conditions.vue': {
      routes:
        | '/stats/conditions'
      views:
        | never
    }
    'src/pages/stats/general.vue': {
      routes:
        | '/stats/general'
      views:
        | never
    }
    'src/pages/stats/possessions.vue': {
      routes:
        | '/stats/possessions'
      views:
        | never
    }
    'src/pages/stats/publications.vue': {
      routes:
        | '/stats/publications'
      views:
        | never
    }
    'src/pages/stats/purchases.vue': {
      routes:
        | '/stats/purchases'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
