name: dumili-api

services:
  kumiko:
    restart: always
    ports:
      - "8005:8080"
    build:
      context: ../../..
      dockerfile: apps/dumili/api/kumiko/Dockerfile
  paddleocr:
    restart: always
    ports:
      - "8006:8081"
    shm_size: "2gb"
    environment:
      PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK: "True"
    volumes:
      - /root/.paddlex
      - ./paddleocr/server.py:/server.py
      - ./paddleocr/recognition_model_rules.json:/recognition_model_rules.json
    build:
      context: ../../..
      dockerfile: apps/dumili/api/paddleocr/Dockerfile
  db:
    container_name: dumili-db
    restart: always
    image: mariadb:12.2
    env_file:
      - .env
    ports:
      - "64097:3306"
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_DATABASE: dumili
      MARIADB_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
