FROM node:26-slim
LABEL org.opencontainers.image.authors="Bruno Perel"
WORKDIR /app

RUN apt-get update && apt-get install -y openssl && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY apps/dumili/api/.env /app/
COPY apps/dumili/api/dist/worker.mjs /app/worker.mjs
COPY apps/dumili/api/dist/instrument.mjs /app/instrument.mjs

CMD ["node", "--import", "./instrument.mjs", "worker.mjs"]
