services:

  pastec-improved:
    container_name: pastec-improved
    image: "bperel/pastec:improved"
    ports:
      - "4213:4212"
    command:
      [
        "-p",
        "4212",
        "-i",
        "/pastec-index-last.dat",
        "/pastec/visualWordsORB.dat",
      ]
    volumes:
      - ./pastec-index-last.dat:/pastec-index-last.dat:ro

  pastec-kp1000-flann200:
    container_name: pastec-kp1000-flann200
    image: "bperel/pastec:kp1000-flann200"
    ports:
      - "4214:4212"
    command:
      [
        "-p",
        "4212",
        "-i",
        "/pastec-index-last.dat",
        "/pastec/visualWordsORB.dat",
      ]
    volumes:
      - ./pastec-index-last.dat:/pastec-index-last.dat:ro

  mailcatcher:
    container_name: mailcatcher
    image: stpaquet/alpinemailcatcher
    platform: linux/386
    ports:
      - "1025:1025"
      - "1080:1080"

volumes:
  node_cache:
