services:
  api:
    container_name: ducksmanager-api
    image: ghcr.io/bperel/ducksmanager-api
    restart: always
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://monitoring-alloy:4318
      - OTEL_SERVICE_NAME=ducksmanager-api
    networks:
      - public-network
      - dm-api-network
      - dm-db-network

  api-websocket:
    container_name: ducksmanager-api-websocket
    image: ghcr.io/bperel/ducksmanager-api:websocket
    restart: always
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://monitoring-alloy:4318
      - OTEL_SERVICE_NAME=ducksmanager-api-websocket
    volumes:
      - ./latest-whattheduck-bundle.txt:/app/latest-whattheduck-bundle.txt
      - /data/covers:${ENTRYURLS_DIR}
      - /data/covers-by-storycode:${ENTRYURLS_DIR}-by-storycode
    networks:
      - public-network
      - dm-api-network
      - dm-db-network

  api-story-search:
    container_name: ducksmanager-api-story-search
    image: ghcr.io/bperel/ducksmanager-api:story-search
    restart: always
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://monitoring-alloy:4318
      - OTEL_SERVICE_NAME=ducksmanager-api-story-search
    volumes:
      - /data/covers:${ENTRYURLS_DIR}
      - /data/covers-by-storycode:${ENTRYURLS_DIR}-by-storycode
    networks:
      - public-network
      - dm-api-network
      - dm-db-network

  pastec-improved:
    container_name: pastec-improved
    image: "bperel/pastec:improved"
    restart: always
    command:
      [
        "-p",
        "4212",
        "-i",
        "/pastec-index-last.dat",
        "/pastec/visualWordsORB.dat",
      ]
    volumes:
      - ./pastec-index-last.dat:/pastec-index-last.dat:ro
    networks:
      - dm-api-network

  pastec-kp1000-flann200:
    container_name: pastec-kp1000-flann200
    image: "bperel/pastec:kp1000-flann200"
    restart: always
    command:
      [
        "-p",
        "4212",
        "-i",
        "/pastec-index-last.dat",
        "/pastec/visualWordsORB.dat",
      ]
    volumes:
      - ./pastec-index-last.dat:/pastec-index-last.dat:ro
    networks:
      - dm-api-network

networks:
  dm-api-network:
    name: dm-api-network
  public-network:
    external: true
  dm-db-network:
    external: true
