apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 30s

  - name: Loki
    type: loki
    access: proxy
    uid: loki
    url: http://loki:3100
