FROM node:26-slim AS build
WORKDIR /app

COPY apps/quackinator/frontend/package.json /app/
RUN npm install

COPY apps/quackinator/frontend /app/
ENV VITE_API_BASE=https://api.quackinator.ducksmanager.net
ENV VITE_DM_STORY_SEARCH_SOCKET_URL=https://api-story-search.ducksmanager.net
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
