/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AiSuggestionIcon: typeof import('./src/components/AiSuggestionIcon.vue')['default']
    BAccordion: typeof import('bootstrap-vue-next')['BAccordion']
    BAccordionItem: typeof import('bootstrap-vue-next')['BAccordionItem']
    BBadge: typeof import('bootstrap-vue-next')['BBadge']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownDivider: typeof import('bootstrap-vue-next')['BDropdownDivider']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BFormSelectOption: typeof import('bootstrap-vue-next')['BFormSelectOption']
    BFormTextarea: typeof import('bootstrap-vue-next')['BFormTextarea']
    BImg: typeof import('bootstrap-vue-next')['BImg']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    Book: typeof import('./src/components/Book.vue')['default']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    BTab: typeof import('bootstrap-vue-next')['BTab']
    BTabs: typeof import('bootstrap-vue-next')['BTabs']
    Entry: typeof import('./src/components/Entry.vue')['default']
    Gallery: typeof import('./src/components/Gallery.vue')['default']
    IBiArrowRight: typeof import('~icons/bi/arrow-right')['default']
    IBiChevronDown: typeof import('~icons/bi/chevron-down')['default']
    IBiInfoCircleFill: typeof import('~icons/bi/info-circle-fill')['default']
    IBiLightbulbFill: typeof import('~icons/bi/lightbulb-fill')['default']
    Issue: typeof import('./src/components/Issue.vue')['default']
    IssueSelect: typeof import('./src/components/IssueSelect.vue')['default']
    IssueSuggestionList: typeof import('./src/components/IssueSuggestionList.vue')['default']
    IssueSuggestionModal: typeof import('./src/components/IssueSuggestionModal.vue')['default']
    Publication: typeof import('./src/components/Publication.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StorySearch: typeof import('./src/components/StorySearch.vue')['default']
    StorySuggestionList: typeof import('./src/components/StorySuggestionList.vue')['default']
    SuggestionList: typeof import('./src/components/SuggestionList.vue')['default']
    TextEditor: typeof import('./src/components/TextEditor.vue')['default']
    UploadWidget: typeof import('./src/components/UploadWidget.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBTooltip: typeof import('bootstrap-vue-next')['vBTooltip']
  }
}
