/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BBadge: typeof import('bootstrap-vue-next')['BBadge']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownDivider: typeof import('bootstrap-vue-next')['BDropdownDivider']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BFormSelectOption: typeof import('bootstrap-vue-next')['BFormSelectOption']
    BFormTextarea: typeof import('bootstrap-vue-next')['BFormTextarea']
    BImg: typeof import('bootstrap-vue-next')['BImg']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    Book: typeof import('./src/components/Book.vue')['default']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    BTab: typeof import('bootstrap-vue-next')['BTab']
    BTabs: typeof import('bootstrap-vue-next')['BTabs']
    Gallery: typeof import('./src/components/Gallery.vue')['default']
    IBiLightbulbFill: typeof import('~icons/bi/lightbulb-fill')['default']
    InducksEntry: typeof import('./src/components/InducksEntry.vue')['default']
    Issue: typeof import('./src/components/Issue.vue')['default']
    IssueSelect: typeof import('./src/components/IssueSelect.vue')['default']
    IssueSuggestionList: typeof import('./src/components/IssueSuggestionList.vue')['default']
    IssueSuggestionModal: typeof import('./src/components/IssueSuggestionModal.vue')['default']
    Publication: typeof import('./src/components/Publication.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadWidget: typeof import('./src/components/UploadWidget.vue')['default']
  }
}
