FROM node:16 as pnpm
LABEL org.opencontainers.image.authors="Bruno Perel"

RUN npm i -g pnpm

FROM pnpm AS app-install
LABEL org.opencontainers.image.authors="Bruno Perel"

WORKDIR /app
COPY package.json pnpm-lock.yaml .eslintrc.js ./
RUN pnpm i

FROM app-install AS api-build
LABEL org.opencontainers.image.authors="Bruno Perel"

WORKDIR /app/api

COPY api/package.json api/pnpm-lock.yaml ./
RUN pnpm i

COPY types /app/types
COPY translations /app/translations
COPY api .
RUN pnpm run build

FROM app-install AS app-build
LABEL org.opencontainers.image.authors="Bruno Perel"

WORKDIR /app

COPY . .
COPY --from=api-build /app/api api
RUN pnpm run build

FROM nginx AS app
LABEL org.opencontainers.image.authors="Bruno Perel"

COPY --from=app-build /app/dist /usr/share/nginx/html

FROM pnpm AS api
LABEL org.opencontainers.image.authors="Bruno Perel"

WORKDIR /app

COPY --from=api-build /app/api/package*.json /app/api/.env.local /app/api/dist /app/
RUN pnpm install --production

EXPOSE 3000
CMD ["node", "index.js"]
