services:
  kumiko:
    restart: always
    ports:
      - "8005:8080"
    build:
      context: kumiko
      dockerfile: Dockerfile
  paddleocr:
    restart: always
    ports:
      - "8006:8081"
    volumes:
      - /root/.paddleocr
    build:
      context: paddleocr
      dockerfile: Dockerfile
  db:
    restart: always
    image: mariadb:11.4
    env_file:
      - ./api/.env
    ports:
      - "64097:3306"
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_DATABASE: dumili
      MARIADB_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
