services:
  kumiko:
    container_name: kumiko
    image: ghcr.io/bperel/kumiko
    restart: always
    networks:
      - dumili-network

  paddleocr:
    container_name: paddleocr
    image: ghcr.io/bperel/paddleocr
    restart: always
    networks:
      - dumili-network

  app:
    container_name: dumili-app
    image: ghcr.io/bperel/dumili-app
    depends_on:
      - api
    restart: always
    networks:
      - public-network
      - dumili-network

  api:
    container_name: dumili-api
    image: ghcr.io/bperel/dumili-api
    restart: always
    networks:
      - public-network
      - dumili-network
      - ducksmanager2_dm2-network

  sentry-relay:
    image: getsentry/relay
    restart: always
    container_name: sentry-dumili
    volumes:
      - ./config/sentry-relay:/work/.relay
    networks:
      - public-network

networks:
  dumili-network:
  ducksmanager2_dm2-network:
    external: true
  public-network:
    external: true
