/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlertNotConnected: typeof import('./src/components/AlertNotConnected.vue')['default']
    AuthorCard: typeof import('./src/components/AuthorCard.vue')['default']
    BAlert: typeof import('bootstrap-vue-next')['BAlert']
    Banner: typeof import('./src/components/Banner.vue')['default']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardBody: typeof import('bootstrap-vue-next')['BCardBody']
    BCardFooter: typeof import('bootstrap-vue-next')['BCardFooter']
    BCardGroup: typeof import('bootstrap-vue-next')['BCardGroup']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    CircleProgressBar: typeof import('./src/components/CircleProgressBar.vue')['default']
    DuckguessrMenu: typeof import('./src/components/DuckguessrMenu.vue')['default']
    Flag: typeof import('./src/components/Flag.vue')['default']
    GameComponent: typeof import('./src/components/GameComponent.vue')['default']
    GameScores: typeof import('./src/components/GameScores.vue')['default']
    GameStartingSoonModal: typeof import('./src/components/GameStartingSoonModal.vue')['default']
    LanguageSwitchDropdown: typeof import('./src/components/LanguageSwitchDropdown.vue')['default']
    Matchmaking: typeof import('./src/components/Matchmaking.vue')['default']
    Medal: typeof import('./src/components/Medal.vue')['default']
    MedalList: typeof import('./src/components/MedalList.vue')['default']
    PlayerInfo: typeof import('./src/components/PlayerInfo.vue')['default']
    PlayerTotalScore: typeof import('./src/components/PlayerTotalScore.vue')['default']
    Podium: typeof import('./src/components/Podium.vue')['default']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    RoundResult: typeof import('./src/components/RoundResult.vue')['default']
    RoundResultModal: typeof import('./src/components/RoundResultModal.vue')['default']
    RoundScore: typeof import('./src/components/RoundScore.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WaitingForPlayers: typeof import('./src/components/WaitingForPlayers.vue')['default']
  }
}
