services:
  db:
    restart: always
    image: mariadb:10.5
    ports:
      - 33061:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: duckguessr
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    networks:
      - dm-server_db-network

networks:
  dm-server_db-network:
    external: true
