name: "Restart DB"

on:
  schedule:
    - cron: "0 0/2 * * *"
  workflow_dispatch:
jobs:
  restart-db:
    runs-on: ubuntu-latest
    environment: production
    env:
      REMOTE_ROOT: apps/dm
      PRODUCTION_SSH_HOST: ${{ secrets.PRODUCTION_SSH_HOST }}
      PRODUCTION_SSH_USER: ${{ secrets.PRODUCTION_SSH_USER }}
      PRODUCTION_SSH_KEY: ${{ secrets.PRODUCTION_SSH_KEY }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          lfs: false

      - name: Install Node.js, pnpm and Bun from mise.toml
        uses: jdx/mise-action@v3

      - name: Install dependencies
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
        run: |
          pnpm -r i

      - name: Restart DB
        timeout-minutes: 5
        run: |
          pnpm -r -F '~prisma-schemas' prod:deploy
