/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArcCircleRender: typeof import('./src/components/renders/ArcCircleRender.vue')['default']
    ConfirmEditMultipleValues: typeof import('./src/components/ConfirmEditMultipleValues.vue')['default']
    Default: typeof import('./src/layouts/default.vue')['default']
    Dimensions: typeof import('./src/components/Dimensions.vue')['default']
    EdgeCanvas: typeof import('./src/components/EdgeCanvas.vue')['default']
    EdgeGallery: typeof import('./src/components/EdgeGallery.vue')['default']
    EdgeLink: typeof import('./src/components/EdgeLink.vue')['default']
    FillRender: typeof import('./src/components/renders/FillRender.vue')['default']
    FormColorInputRow: typeof import('./src/components/FormColorInputRow.vue')['default']
    FormInputRow: typeof import('./src/components/FormInputRow.vue')['default']
    Gallery: typeof import('./src/components/Gallery.vue')['default']
    GradientRender: typeof import('./src/components/renders/GradientRender.vue')['default']
    ImageRender: typeof import('./src/components/renders/ImageRender.vue')['default']
    Issue: typeof import('./src/components/from-dm/Issue.vue')['default']
    IssueSelect: typeof import('./src/components/IssueSelect.vue')['default']
    Medal: typeof import('./src/components/from-dm/Medal.vue')['default']
    MedalProgress: typeof import('./src/components/from-dm/MedalProgress.vue')['default']
    ModelEdit: typeof import('./src/components/ModelEdit.vue')['default']
    MultipleTargetOptions: typeof import('./src/components/MultipleTargetOptions.vue')['default']
    PolygonRender: typeof import('./src/components/renders/PolygonRender.vue')['default']
    Popover: typeof import('./src/components/Popover.vue')['default']
    PositionHelper: typeof import('./src/components/PositionHelper.vue')['default']
    Publication: typeof import('./src/components/from-dm/Publication.vue')['default']
    PublishedEdge: typeof import('./src/components/PublishedEdge.vue')['default']
    RectangleRender: typeof import('./src/components/renders/RectangleRender.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveModelButton: typeof import('./src/components/SaveModelButton.vue')['default']
    SessionInfo: typeof import('./src/components/SessionInfo.vue')['default']
    StapleRender: typeof import('./src/components/renders/StapleRender.vue')['default']
    TextRender: typeof import('./src/components/renders/TextRender.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    Upload: typeof import('./src/components/Upload.vue')['default']
    UploadableEdgesCarousel: typeof import('./src/components/from-dm/UploadableEdgesCarousel.vue')['default']
  }
}
